      - name: Configure Git to handle long paths
        run: |
          git config --global core.protectNTFS false
          git config --global core.protectHFS false
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 1
        env:
          GIT_CONFIG_GLOBAL_CORE_PROTECTNTFS: false
          GIT_CONFIG_GLOBAL_CORE_PROTECTHFS: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5